import { NextResponse } from 'next/server';
import { db } from '@/lib/firebase';
import { collection, getDocs, doc, setDoc } from 'firebase/firestore';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export const ALL_SERVICES = [
  // 6 Primary Services
  {
    id: 'svc-quantity-takeoff',
    slug: 'quantity-takeoff',
    title: 'Quantity Takeoff',
    category: 'Primary Service',
    short: 'Detailed CSI-coded takeoffs from drawings — concrete, steel, masonry, MEP and more.',
    tagline: 'Precise, CSI-coded material quantities pulled straight from your drawings.',
    includes: 'Full plan & specification review; Color-coded on-screen markups by trade; Concrete, masonry, steel, wood, finishes & MEP; Waste and lap factors applied; RFI log for missing or unclear scope',
    deliverables: 'CSI-coded Excel workbook; Marked-up PDF plan set; Summary sheet by division',
    overview: 'Our quantity takeoff service measures every material in your plans down to the line item, organized by CSI division so the numbers are easy to price and easy to defend.',
    status: 'Published',
  },
  {
    id: 'svc-material-estimation',
    slug: 'material-estimation',
    title: 'Material Estimation',
    category: 'Primary Service',
    short: 'Accurate material lists with current regional pricing and waste factors.',
    tagline: 'Procurement-ready material lists priced to your local market.',
    includes: 'Itemized bill of materials (BOM); Current regional supplier pricing; Waste, lap and coverage factors; Labor hours by item where required; Alternates and substitution options',
    deliverables: 'Procurement-ready BOM in Excel; Priced summary by category; Supplier-ready order sheets',
    overview: 'We turn your drawings into a complete bill of materials with current regional pricing, so you know exactly what to buy and what it will cost.',
    status: 'Published',
  },
  {
    id: 'svc-residential-estimation',
    slug: 'residential-estimation',
    title: 'Residential Estimation',
    category: 'Primary Service',
    short: 'Single-family, multi-family and remodel estimates that win bids.',
    tagline: 'Bid-ready estimates for custom homes, multi-family and remodels.',
    includes: 'Single-family, multi-family & townhomes; Renovations, additions & remodels; Allowance and option pricing; Site work and foundations; Finishes and cabinetry',
    deliverables: 'Line-item residential estimate; Excel + PDF summary; Marked-up plans',
    overview: 'From custom single-family homes to multi-family communities and renovations, we build detailed residential estimates that hold up to owner and lender scrutiny.',
    status: 'Published',
  },
  {
    id: 'svc-commercial-estimation',
    slug: 'commercial-estimation',
    title: 'Commercial Estimation',
    category: 'Primary Service',
    short: 'Office, retail, healthcare and industrial estimates with full bid packages.',
    tagline: 'Full bid packages for office, retail, healthcare and industrial projects.',
    includes: 'Ground-up shell & core; Tenant improvements; GMP and hard-bid packages; Structural, envelope and MEP; Value-engineering options',
    deliverables: 'Full commercial bid package; CSI-coded Excel estimate; Executive summary & assumptions',
    overview: 'We support general contractors and subs on commercial work of every size — from tenant improvements to ground-up shell and core — with complete, well-organized estimates.',
    status: 'Published',
  },
  {
    id: 'svc-bid-preparation',
    slug: 'bid-preparation',
    title: 'Bid Preparation',
    category: 'Primary Service',
    short: 'Bid-ready documents formatted to your template, with executive summaries.',
    tagline: 'Polished, submission-ready bid packages built to win.',
    includes: 'Sub-bid leveling and comparison; Proposal formatting to your template; Executive summary and cover letter; Inclusions / exclusions and assumptions; Final review before submission',
    deliverables: 'Submission-ready bid package; Leveled sub-bid comparison; Cover letter & executive summary',
    overview: 'We assemble your numbers into a clean, professional bid package formatted to your template and ready to submit on deadline.',
    status: 'Published',
  },
  {
    id: 'svc-trade-specific-estimates',
    slug: 'trade-specific-estimates',
    title: 'Trade-Specific Estimates',
    category: 'Primary Service',
    short: 'Specialized takeoffs for trades — concrete, drywall, painting, roofing, MEP.',
    tagline: 'Specialized takeoffs and estimates for individual trades.',
    includes: 'Concrete & masonry; Drywall, framing & finishes; Painting & coatings; Roofing & waterproofing; Mechanical, electrical & plumbing',
    deliverables: 'Trade-specific takeoff & estimate; Excel workbook by scope; Marked-up plans for your trade',
    overview: 'Subcontractors get focused, trade-specific takeoffs and estimates built around exactly the scope they self-perform.',
    status: 'Published',
  },

  // 29 Trade Estimating Services
  {
    id: 'svc-concrete-estimating',
    slug: 'concrete-estimating',
    title: 'Concrete Estimating Services',
    category: 'Trade Estimating',
    short: 'Accurate concrete quantities and pricing for foundations, slabs, walls and structures.',
    tagline: 'Footings, slabs, walls, rebar and formwork priced to your local market.',
    includes: 'Spread & continuous footings; Foundation walls & grade beams; Slabs-on-grade & elevated decks; Formwork, rebar & embeds; Placing, finishing & pumping',
    deliverables: 'CSI Division 03 Excel workbook; Marked-up plans by pour; Concrete summary by mix & strength',
    overview: 'Our concrete estimators measure every cubic yard of your project — footings, foundations, slabs-on-grade, elevated decks, retaining walls, columns and beams — and price it with current regional material and labor rates.',
    status: 'Published',
  },
  {
    id: 'svc-electrical-estimating',
    slug: 'electrical-estimating',
    title: 'Electrical Estimating Services',
    category: 'Trade Estimating',
    short: 'Complete electrical takeoffs — from service entrance to the last device.',
    tagline: 'Panels, feeders, branch circuits, lighting and low-voltage priced to your market.',
    includes: 'Service entrance, switchgear & panels; Feeders, branch circuits & conduit; Lighting fixtures & controls; Devices, receptacles & switches; Fire alarm & low-voltage pathways',
    deliverables: 'CSI Division 26 Excel estimate; Marked-up plans by circuit; Labor hours & material summary',
    overview: 'We produce detailed electrical estimates covering power distribution, lighting, devices, conduit and wire, panels, gear and controls, priced to your local labor and material market.',
    status: 'Published',
  },
  {
    id: 'svc-electrical-estimating-outsourcing',
    slug: 'electrical-estimating-outsourcing',
    title: 'Electrical Estimating Outsourcing',
    category: 'Trade Estimating',
    short: 'A dedicated electrical estimating team without the overhead of hiring one.',
    tagline: 'On-demand pre-construction department ready when bid invites arrive.',
    includes: 'On-demand estimating capacity; Consistent formats across every bid; Fast turnaround on bid invites; Scalable during busy seasons; Confidential NDA on every project',
    deliverables: 'Bid-ready electrical estimate; Marked-up plans & takeoff sheets; Proposal-ready summary',
    overview: 'Electrical contractors outsource their estimating to us to bid more work without adding payroll. We become your on-demand pre-construction department.',
    status: 'Published',
  },
  {
    id: 'svc-telecom-estimating-services',
    slug: 'telecom-estimating-services',
    title: 'Telecom Estimating Services',
    category: 'Trade Estimating',
    short: 'Structured cabling, fiber and telecom infrastructure quantified and priced.',
    tagline: 'Copper & fiber backbone, horizontal cabling, racks and pathways.',
    includes: 'Copper & fiber backbone cabling; Horizontal cabling & data drops; Racks, cabinets & patch panels; Cable tray, conduit & pathways; Terminations, testing & labeling',
    deliverables: 'CSI Division 27 estimate; Drop count schedule; Material & labor summary',
    overview: 'We estimate telecommunications and structured cabling scopes — copper and fiber backbone, horizontal cabling, racks, pathways and terminations.',
    status: 'Published',
  },
  {
    id: 'svc-interior-exterior-finishes',
    slug: 'interior-exterior-finishes',
    title: 'Interior & Exterior Finishes Estimating',
    category: 'Trade Estimating',
    short: 'Drywall, flooring, paint and finish scopes measured room by room to the square foot.',
    tagline: 'Drywall, flooring, painting, ceilings and cladding measured room by room.',
    includes: 'Metal framing & drywall by type; Taping & finish levels; Flooring — tile, carpet, LVT, wood; Painting & wall coverings; Ceilings & acoustical systems',
    deliverables: 'CSI Division 09 estimate; Room-by-room finish schedule; Marked-up plans by finish',
    overview: 'Finishes are where scope hides. We measure every wall, ceiling and floor area by room, finish type and substrate so your finish estimates are complete.',
    status: 'Published',
  },
  {
    id: 'svc-drywall-takeoff-services',
    slug: 'drywall-takeoff-services',
    title: 'Drywall Takeoff Services',
    category: 'Trade Estimating',
    short: 'Board, framing, tape and finish quantified for every wall and ceiling.',
    tagline: 'Count every sheet, stud, track and pound of compound.',
    includes: 'Metal stud & track framing; Drywall sheets by type & rating; Taping, mud & corner beads; Insulation & sound attenuation; Soffits, bulkheads & shaft walls',
    deliverables: 'CSI Division 09 drywall takeoff; Stud & board count sheet; Marked-up wall plans',
    overview: 'Our drywall takeoffs count every sheet, stud, track and pound of compound. We separate wall types, fire ratings and finish levels so pricing reflects actual scope.',
    status: 'Published',
  },
  {
    id: 'svc-flooring-estimating-services',
    slug: 'flooring-estimating-services',
    title: 'Flooring Estimating Services',
    category: 'Trade Estimating',
    short: 'Tile, carpet, LVT, hardwood and resilient flooring taken off by area and room.',
    tagline: 'Exact square footage, waste factors and transition counts by room.',
    includes: 'Carpet & carpet tile; LVT, sheet vinyl & VCT; Tile, stone & grout; Hardwood & engineered wood; Base, transition strips & floor prep',
    deliverables: 'CSI Division 09 flooring takeoff; Room-by-room area schedule; Material order list with waste',
    overview: 'Detailed flooring estimates broken out by room, material type and substrate preparation.',
    status: 'Published',
  },
  {
    id: 'svc-painting-estimating-services',
    slug: 'painting-estimating-services',
    title: 'Painting Estimating Services',
    category: 'Trade Estimating',
    short: 'Interior and exterior paint quantities, coats, surface prep and trim counted.',
    tagline: 'Surface area by substrate, finish level, coats and prep.',
    includes: 'Interior walls & ceilings; Doors, frames & trim; Exterior siding & masonry; Primers, sealers & coats; Surface prep & masking',
    deliverables: 'Painting estimate by surface type; Gallon count summary; Labor & equipment hours',
    overview: 'Complete paint takeoffs covering square footage, coat counts, surface preparation, primer and finish coats.',
    status: 'Published',
  },
  {
    id: 'svc-masonry-estimating',
    slug: 'masonry-estimating',
    title: 'Masonry Estimating Services',
    category: 'Trade Estimating',
    short: 'Masonry unit counts from elevations — CMU, brick, stone, mortar, grout and rebar.',
    tagline: 'CMU, brick, stone veneer, mortar, grout and reinforcing counted.',
    includes: 'CMU by size & wall type; Brick & modular units; Stone & manufactured veneer; Mortar, grout & reinforcing; Lintels, flashing & control joints',
    deliverables: 'CSI Division 04 workbook; Unit count by wall & elevation; Rebar & grout summary',
    overview: 'Masonry bids live or die on unit counts. Modern Estimator provides masonry estimating services that count every block, brick and stone.',
    status: 'Published',
  },
  {
    id: 'svc-mep-estimating',
    slug: 'mep-estimating',
    title: 'MEP Estimating Services',
    category: 'Trade Estimating',
    short: 'Coordinated MEP estimating services from trade-specialist estimators.',
    tagline: 'HVAC, plumbing, piping and electrical quantified in one bid package.',
    includes: 'HVAC ductwork, equipment & controls; Plumbing fixtures, piping & drains; Electrical distribution, lighting & devices; Process piping & medical gas; Coordination & scope-gap review',
    deliverables: 'Unified MEP Excel workbook; Trade-by-trade cost summary; Marked-up MEP drawings',
    overview: 'MEP is the most detail-heavy part of any estimate. We take off mechanical, electrical and plumbing scopes separately and coordinate them.',
    status: 'Published',
  },
  {
    id: 'svc-mechanical-estimating',
    slug: 'mechanical-estimating',
    title: 'Mechanical Estimating',
    category: 'Trade Estimating',
    short: 'HVAC equipment, ductwork, piping and controls quantified and priced.',
    tagline: 'Chillers, RTUs, boilers, ductwork and piping taken off accurately.',
    includes: 'Air handling units, RTUs & chillers; Ductwork & fittings by gauge; Hydronic piping & pumps; Air devices & dampers; Temperature controls & BACnet',
    deliverables: 'CSI Division 23 mechanical estimate; Duct weight & equipment schedule; Labor & fitting summary',
    overview: 'HVAC equipment, ductwork weight by gauge, fittings and temperature control systems priced to your regional labor rates.',
    status: 'Published',
  },
  {
    id: 'svc-hvac-estimating',
    slug: 'hvac-estimating',
    title: 'HVAC Estimating',
    category: 'Trade Estimating',
    short: 'Ductwork tonnage, equipment, grilles and controls measured from mechanical plans.',
    tagline: 'Duct weight, fitting counts and HVAC equipment takeoff.',
    includes: 'Supply, return & exhaust ductwork; Sheet metal fittings & transitions; Diffusers, registers & grilles; Rooftop units, VRF & split systems; Insulation & acoustic lining',
    deliverables: 'HVAC takeoff & cost estimate; Sheet metal poundage list; Equipment schedule & pricing',
    overview: 'Complete HVAC takeoffs covering air distribution, sheet metal poundage, equipment and insulation.',
    status: 'Published',
  },
  {
    id: 'svc-duct-takeoff-services',
    slug: 'duct-takeoff-services',
    title: 'Duct Takeoff Services',
    category: 'Trade Estimating',
    short: 'Sheet metal ductwork pounds, square footage and fittings counted by gauge.',
    tagline: 'Precise duct weight and fitting counts for mechanical contractors.',
    includes: 'Rectangular, round & spiral ductwork; Sheet metal gauge & pressure class; Elbows, tees, reducers & transitions; Dampers, vanes & flex duct; Hangers, insulation & sealants',
    deliverables: 'Detailed duct takeoff spreadsheet; Weight break by gauge & size; Fitting summary sheet',
    overview: 'Sheet metal ductwork taken off by gauge, pressure class and dimension with exact fitting counts.',
    status: 'Published',
  },
  {
    id: 'svc-plumbing-estimating',
    slug: 'plumbing-estimating',
    title: 'Plumbing Estimating',
    category: 'Trade Estimating',
    short: 'Water, waste, vent, gas lines and fixture counts from plumbing riser diagrams.',
    tagline: 'Fixtures, piping runs, drains and equipment accurately estimated.',
    includes: 'Domestic cold & hot water piping; Sanitary waste & vent piping; Natural gas & LPG piping; Plumbing fixtures & trim; Water heaters, pumps & backflow',
    deliverables: 'CSI Division 22 plumbing estimate; Fixture & pipe takeoff schedule; Material & labor summary',
    overview: 'Plumbing takeoffs covering domestic water, waste, vent, gas, fixtures and equipment from plans and riser diagrams.',
    status: 'Published',
  },
  {
    id: 'svc-piping-estimating',
    slug: 'piping-estimating',
    title: 'Piping Estimating',
    category: 'Trade Estimating',
    short: 'Process, hydronic and utility piping taken off by size, schedule and material.',
    tagline: 'Steel, copper, PVC and stainless piping runs with valves and fittings.',
    includes: 'Hydronic heating & chilled water piping; Compressed air & fuel piping; Valves, strainers & specialties; Hangers, supports & insulation; Welding & joint counts',
    deliverables: 'Piping takeoff & pricing workbook; Valve & fitting schedule; Weld count & labor units',
    overview: 'Process, hydronic and industrial piping runs measured with valve schedules, fittings and weld counts.',
    status: 'Published',
  },
  {
    id: 'svc-gutter-estimating',
    slug: 'gutter-estimating',
    title: 'Gutter Estimating Services',
    category: 'Trade Estimating',
    short: 'Commercial and residential gutter, downspout and drainage takeoffs.',
    tagline: 'Seamless gutters, downspouts, scuppers and conductor heads.',
    includes: 'Commercial & residential gutters; Downspouts & conductor heads; Scuppers & overflow drains; Hangers, elbows & splash blocks; Custom metal fabrication',
    deliverables: 'Gutter takeoff & quote summary; Linear footage & fitting count; Material order sheet',
    overview: 'Linear footage, downspouts, conductor heads and custom flashing for roof drainage systems.',
    status: 'Published',
  },
  {
    id: 'svc-metals-estimating',
    slug: 'metals-estimating',
    title: 'Metals Estimating Services',
    category: 'Trade Estimating',
    short: 'Structural steel, rebar, metal deck, stairs, railings and miscellaneous metals.',
    tagline: 'Steel tonnage, rebar weight and fabrication pricing from structural drawings.',
    includes: 'Structural steel beams, columns & trusses; Metal deck & stud shear connectors; Rebar by size, weight & grade; Miscellaneous metals, stairs & railings; Erection & shop painting labor',
    deliverables: 'CSI Division 05 metals estimate; Steel tonnage & rebar weight summary; Connections & misc metals schedule',
    overview: 'Structural steel tonnage, metal decking, rebar and miscellaneous metal fabrications measured from structural plans.',
    status: 'Published',
  },
  {
    id: 'svc-rebar-estimating',
    slug: 'rebar-estimating',
    title: 'Rebar Estimating Services',
    category: 'Trade Estimating',
    short: 'Reinforcing steel tonnage, bar lists, stirrups and mesh taken off per element.',
    tagline: 'Bar-by-bar rebar schedule with weight by size and grade.',
    includes: 'Deformed bar by size (#3 to #18); Rebar grade (Grade 60, epoxy, stainless); Welded wire reinforcement (WWR); Stirrups, ties & dowels; Lap lengths & waste factors',
    deliverables: 'Rebar takeoff & bending list; Weight summary by bar size; Placement & accessory list',
    overview: 'Bar-by-bar rebar scheduling with tonnage by size, grade and structural element.',
    status: 'Published',
  },
  {
    id: 'svc-structural-steel-estimating-services',
    slug: 'structural-steel-estimating-services',
    title: 'Structural Steel Estimating Services',
    category: 'Trade Estimating',
    short: 'Fabrication and erection steel tonnage, connection plates and joist takeoffs.',
    tagline: 'Beams, columns, joists, deck and connection steel priced.',
    includes: 'W-shapes, channels, angles & HSS; Steel joists & joist girders; Metal roof & floor deck; Moment & shear connections; Shop primer & erection labor',
    deliverables: 'Structural steel bid package; Tonnage takeoff by member type; Fabrication & erection estimate',
    overview: 'Structural member weights, connection plates, joists and erection labor for steel fabricators and erectors.',
    status: 'Published',
  },
  {
    id: 'svc-openings-estimating',
    slug: 'openings-estimating',
    title: 'Openings Estimating Services',
    category: 'Trade Estimating',
    short: 'Doors, frames, hardware sets, windows, storefront and curtain wall counted.',
    tagline: 'Door schedule, frame count and hardware set matching.',
    includes: 'Hollow metal & wood doors; Steel & aluminum frames; Hardware sets by schedule; Windows, storefront & curtain wall; Glazing, louvers & specialty doors',
    deliverables: 'CSI Division 08 openings estimate; Door & hardware schedule matrix; Glazing & frame breakdown',
    overview: 'Complete Division 08 takeoffs reconciling door schedules, hardware sets, aluminum storefront and glazing.',
    status: 'Published',
  },
  {
    id: 'svc-thermal-moisture-protection-estimating',
    slug: 'thermal-moisture-protection-estimating',
    title: 'Thermal & Moisture Protection Estimating',
    category: 'Trade Estimating',
    short: 'Division 07 estimating — roofing, insulation, waterproofing, air barriers and sealants.',
    tagline: 'Roofing, insulation, waterproofing and fireproofing measured from details.',
    includes: 'Commercial & residential roofing; Rigid & batt insulation; Below-grade waterproofing; Air & vapor barriers; Joint sealants & expansion joints',
    deliverables: 'CSI Division 07 estimate; Square footage schedule by roof & wall area; Material & flashing breakdown',
    overview: 'Thermal and moisture protection systems measured from architectural details and roof plans.',
    status: 'Published',
  },
  {
    id: 'svc-insulation-estimating-services',
    slug: 'insulation-estimating-services',
    title: 'Insulation Estimating Services',
    category: 'Trade Estimating',
    short: 'Batt, blown-in, spray foam and rigid board insulation measured by area and R-value.',
    tagline: 'Wall, attic and pipe insulation taken off by R-value.',
    includes: 'Fiberglass batt & mineral wool; Spray polyurethane foam (SPF); Rigid board (XPS/Polyiso); Pipe & duct thermal insulation; Sound attenuation batts',
    deliverables: 'Insulation takeoff spreadsheet; Square footage by R-value; Material order & labor estimate',
    overview: 'Thermal and acoustical insulation takeoffs categorized by R-value, material type and location.',
    status: 'Published',
  },
  {
    id: 'svc-roofing-estimating',
    slug: 'roofing-estimating',
    title: 'Roofing Estimating Services',
    category: 'Trade Estimating',
    short: 'Single-ply, metal, shingle and built-up roofing estimates with flashings.',
    tagline: 'TPO, EPDM, metal roofing, shingles and flashing accessories.',
    includes: 'TPO, EPDM & PVC single-ply membranes; Standing seam metal roofing; Asphalt shingles & tile; Roof insulation & cover board; Coping, flashing & roof drains',
    deliverables: 'Roofing estimate workbook; Square count & pitch calculation; Accessory & edge detail list',
    overview: 'Commercial and residential roof square counts, pitch adjustments, membrane, insulation and edge metal accessories.',
    status: 'Published',
  },
  {
    id: 'svc-fireproofing-estimating-services',
    slug: 'fireproofing-estimating-services',
    title: 'Fireproofing Estimating Services',
    category: 'Trade Estimating',
    short: 'Intumescent paint and sprayed fire-resistive materials (SFRM) measured by beam.',
    tagline: 'Spray fireproofing and intumescent coating coverage.',
    includes: 'Cementitious & fibrous SFRM; Intumescent fire-resistive coatings; Steel beam, column & deck area; Hourly rating matching (1-hr, 2-hr, 3-hr); Over-spray & thickness factors',
    deliverables: 'Fireproofing takeoff sheet; Board foot / square foot summary; Material thickness & labor cost',
    overview: 'Sprayed fire-resistive material and intumescent coating coverage calculated from structural steel member sizes.',
    status: 'Published',
  },
  {
    id: 'svc-sitework-estimating',
    slug: 'sitework-estimating',
    title: 'Sitework Estimating Services',
    category: 'Trade Estimating',
    short: 'Demolition, cut/fill earthwork, site utilities, paving, curbs and site improvements.',
    tagline: 'Earthwork cut/fill, site utilities and paving quantified from civil drawings.',
    includes: 'Site clearing & earthwork cut/fill; Storm & sanitary sewer utilities; Water mains & service lines; Asphalt paving, concrete curbs & sidewalks; Erosion control & site prep',
    deliverables: 'CSI Division 31-33 sitework estimate; Cut/fill volume summary; Utility pipe & structure schedule',
    overview: 'Civil drawings takeoff for earthwork cut/fill volumes, site utilities, paving and site improvements.',
    status: 'Published',
  },
  {
    id: 'svc-landscaping-estimating-services',
    slug: 'landscaping-estimating-services',
    title: 'Landscaping Estimating Services',
    category: 'Trade Estimating',
    short: 'Hardscape, plantings, irrigation and sod measured from landscape plans.',
    tagline: 'Plants, trees, sod, irrigation heads and paver hardscapes.',
    includes: 'Trees, shrubs & groundcover counts; Sod, hydroseed & topsoil depth; Irrigation piping, valves & heads; Pavers, retaining walls & edging; Mulch, gravel & decorative stone',
    deliverables: 'Landscaping takeoff & cost sheet; Plant count schedule; Material volume & labor breakdown',
    overview: 'Plant counts, turf area, topsoil volumes, irrigation heads and paver hardscaping quantified from landscape plans.',
    status: 'Published',
  },
  {
    id: 'svc-lumber-takeoff',
    slug: 'lumber-takeoff',
    title: 'Lumber Takeoff Services',
    category: 'Trade Estimating',
    short: 'Lumber takeoff services for framers and builders — studs, joists, rafters and sheathing.',
    tagline: 'Framing material lists ready to order from the lumber yard.',
    includes: 'Wall studs, plates & headers; Floor joists, I-joists & trusses; Roof rafters, hips & valleys; OSB & plywood sheathing; Engineered lumber (LVL, PSL, Glulam)',
    deliverables: 'Stick-by-stick lumber list; Cut list & length optimization; Sheathing sheet count & waste',
    overview: 'A lumber list that is accurate to the stick — studs, plates, headers, joists, rafters and sheathing optimized for lumber yard ordering.',
    status: 'Published',
  },
  {
    id: 'svc-wood-plastic-composites-estimating',
    slug: 'wood-plastic-composites-estimating',
    title: 'Wood & Plastic Composites Estimating',
    category: 'Trade Estimating',
    short: 'Rough carpentry, composite decking, architectural woodwork and plastic fabrications.',
    tagline: 'Framing, composite decking, railing and exterior trim.',
    includes: 'Rough carpentry & blocking; Composite decking & railing systems; PVC exterior trim & fascia; Plastic fabrications & wall paneling; Hardware, fasteners & ties',
    deliverables: 'CSI Division 06 estimate; Decking & framing takeoff sheet; Material list with fasteners',
    overview: 'Rough carpentry, exterior PVC trim, composite decking systems and structural plastic fabrications.',
    status: 'Published',
  },
  {
    id: 'svc-millwork-estimating',
    slug: 'millwork-estimating',
    title: 'Millwork Estimating Services',
    category: 'Trade Estimating',
    short: 'Custom casework, cabinets, trim, moulding and architectural wood paneling.',
    tagline: 'Casework, countertops, moulding and custom architectural woodwork.',
    includes: 'Commercial casework & cabinets; Plastic laminate & solid surface tops; Standing & running trim/moulding; Architectural wall paneling & wainscot; Custom reception desks & features',
    deliverables: 'Millwork & casework estimate; Linear & square foot itemization; Hardware & finish breakdown',
    overview: 'Custom architectural millwork, commercial casework, countertops, running trim and decorative wall paneling.',
    status: 'Published',
  },
];

export async function GET() {
  try {
    const servicesRef = collection(db, 'services');
    const snapshot = await getDocs(servicesRef);

    let services = snapshot.docs.map((d) => ({
      ...d.data(),
      id: d.id,
    }));

    // If database services collection is empty, auto-seed with all 35 user-side services!
    if (services.length === 0) {
      console.log('Seeding initial 35 user-side services into Firestore DB...');
      for (const svc of ALL_SERVICES) {
        await setDoc(doc(db, 'services', svc.id), svc);
      }
      services = ALL_SERVICES;
    }

    return NextResponse.json({ services });
  } catch (error) {
    console.error('Error fetching services:', error);
    return NextResponse.json({ error: 'Failed to fetch services', details: error.message }, { status: 500 });
  }
}

export async function POST(request) {
  try {
    const body = await request.json();
    const {
      title, slug, category, tagline, short, h1, metaTitle, metaDescription,
      overview, points, includes, deliverables, whoWeServe, relatedServices, faqs, status
    } = body;

    if (!title || !title.trim()) {
      return NextResponse.json({ error: 'Service title is required' }, { status: 400 });
    }

    const cleanSlug = (slug || title).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const serviceId = `svc-${cleanSlug || Date.now().toString(36)}`;

    const newService = {
      id: serviceId,
      slug: cleanSlug,
      title: title.trim(),
      category: category || 'Primary Service',
      tagline: tagline ? tagline.trim() : '',
      short: short ? short.trim() : '',
      h1: h1 ? h1.trim() : `${title.trim()} Services`,
      metaTitle: metaTitle ? metaTitle.trim() : `${title.trim()} | Modern Estimator`,
      metaDescription: metaDescription ? metaDescription.trim() : (short ? short.trim() : tagline ? tagline.trim() : ''),
      overview: overview ? overview.trim() : '',
      points: points ? points.trim() : '',
      includes: includes ? includes.trim() : '',
      deliverables: deliverables ? deliverables.trim() : '',
      whoWeServe: whoWeServe ? whoWeServe.trim() : '',
      relatedServices: relatedServices ? relatedServices.trim() : '',
      faqs: faqs ? faqs.trim() : '',
      status: status || 'Published',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await setDoc(doc(db, 'services', serviceId), newService);

    return NextResponse.json({ success: true, service: newService });
  } catch (error) {
    console.error('Error creating service:', error);
    return NextResponse.json({ error: 'Failed to create service', details: error.message }, { status: 500 });
  }
}
