import { NextResponse } from 'next/server';
import { db } from '@/lib/firebase';
import { collection, getDocs, doc, setDoc } from 'firebase/firestore';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export const ALL_TRADES = [
  // 10 Parent Trades + 19 Sub-Trades = 29 Total Trade Pages
  {
    id: 'trd-concrete-estimating',
    slug: 'concrete-estimating',
    title: 'Concrete Estimating',
    parent: '—',
    tagline: 'Accurate concrete quantities and pricing for foundations, slabs, walls and structures.',
    h1: 'Concrete Estimating Services',
    metaTitle: 'Concrete Estimating Services | Takeoffs in 8–24 Hrs',
    metaDescription: 'Accurate concrete estimating and takeoff services for contractors — footings, slabs, walls, rebar and formwork priced to your local market. Delivered in 8–24 hours.',
    intro: 'Concrete is usually the first major cost on a project and the hardest to recover if you get it wrong. Modern Estimator delivers detailed concrete estimating services that measure every cubic yard, every pound of rebar and every square foot of formwork directly from your structural and architectural drawings.',
    scope: 'Structural elements: Spread & continuous footings; Foundation walls & grade beams; Slabs-on-grade & toppings; Elevated slabs & decks; Columns, piers & beams | Reinforcing & forming: Rebar by size, weight & element; Welded wire mesh & dowels; Formwork area & reuse factors; Anchor bolts & embeds | Placing & finishing: Concrete by mix & strength; Pumping & placement; Finishing, curing & sealing; Joints & waterstops',
    serve: 'Concrete contractors; General contractors; Foundation & flatwork subs; Ready-mix suppliers; Developers & builders',
    deliverables: 'CSI Division 03 Excel workbook; Marked-up plans by pour; Concrete summary by mix & strength',
    relatedServices: 'quantity-takeoff; material-estimation; commercial-estimation',
    faqs: 'Q: What do you need to start a concrete estimate?\nA: Structural drawings, foundation and framing plans, sections and details.\n\nQ: Do you calculate rebar and formwork separately?\nA: Yes. Rebar is taken off by bar size and weight, and formwork is measured as contact area.\n\nQ: How accurate are your concrete quantities?\nA: Our concrete takeoffs are accurate to within ±2%.',
    status: 'Published',
  },
  {
    id: 'trd-electrical-estimating',
    slug: 'electrical-estimating',
    title: 'Electrical Estimating',
    parent: '—',
    tagline: 'Complete electrical takeoffs — from service entrance to the last device.',
    h1: 'Electrical Estimating Services',
    metaTitle: 'Electrical Estimating Services | Bid-Ready in 8–24 Hrs',
    metaDescription: 'Professional electrical estimating and takeoff services — panels, feeders, branch circuits, lighting, devices and low-voltage priced to your market. 8–24 hour turnaround.',
    intro: 'Electrical scopes carry hundreds of small items that add up fast, and missing a run of conduit or a lighting package can wipe out a margin. Modern Estimator provides electrical estimating services that capture every circuit, device and fixture from the power, lighting and one-line drawings.',
    scope: 'Distribution: Service entrance & metering; Switchgear, panels & transformers; Feeders & conduit by size | Branch & lighting: Branch circuits, wire & boxes; Lighting fixtures by type; Lighting controls & sensors; Receptacles & switches | Systems: Fire alarm rough-in; Data & telecom pathways; Security & access control',
    serve: 'Electrical contractors; General contractors; Design-build firms; Low-voltage & systems integrators',
    deliverables: 'CSI Division 26 Excel estimate; Marked-up plans by circuit; Labor hours & material summary',
    relatedServices: 'quantity-takeoff; commercial-estimation; bid-preparation',
    faqs: 'Q: Do you estimate from one-line diagrams as well as plans?\nA: Yes. We use the one-line, panel schedules, lighting plans and power plans together.\n\nQ: Do you include labor hours?\nA: Every electrical estimate includes labor units by item, adjusted to your local wage rates.',
    status: 'Published',
  },
  {
    id: 'trd-electrical-estimating-outsourcing',
    slug: 'electrical-estimating-outsourcing',
    title: 'Electrical Estimating Outsourcing',
    parent: 'Electrical Estimating',
    tagline: 'A dedicated electrical estimating team, without the overhead of hiring one.',
    h1: 'Electrical Estimating Outsourcing Services',
    metaTitle: 'Outsource Electrical Estimating | On-Demand Pre-Construction',
    metaDescription: 'Outsource your electrical estimating to trade specialists. Bid more jobs with no added payroll. 8–24 hour turnaround on bid invites.',
    intro: 'Electrical contractors outsource their estimating to us to bid more work without adding payroll. We become your on-demand pre-construction department, ready when the bid invites arrive.',
    scope: 'Capacity: On-demand estimating capacity; Consistent formats across every bid; Fast turnaround on bid invites; Scalable during busy seasons; Confidential NDA on every project',
    serve: 'Electrical contractors; Independent electricians; Commercial electrical subs',
    deliverables: 'Bid-ready electrical estimate; Marked-up plans & takeoff sheets; Proposal-ready summary',
    relatedServices: 'electrical-estimating; bid-preparation',
    faqs: 'Q: How does outsourcing work?\nA: Send us your plans via email or cloud link. We deliver a complete estimate formatted to your standards within 8–24 hours.',
    status: 'Published',
  },
  {
    id: 'trd-telecom-estimating-services',
    slug: 'telecom-estimating-services',
    title: 'Telecom Estimating Services',
    parent: 'Electrical Estimating',
    tagline: 'Structured cabling, fiber and telecom infrastructure quantified and priced.',
    h1: 'Telecom & Structured Cabling Estimating',
    metaTitle: 'Telecom Estimating Services | Structured Cabling & Fiber',
    metaDescription: 'Telecom and structured cabling estimating — copper and fiber backbone, data drops, racks, cable tray and terminations priced to your market.',
    intro: 'We estimate telecommunications and structured cabling scopes — copper and fiber backbone, horizontal cabling, racks, pathways and terminations — for commercial and institutional projects.',
    scope: 'Backbone & horizontal: Copper & fiber backbone cabling; Horizontal cabling & data drops | Racks & pathways: Racks, cabinets & patch panels; Cable tray, conduit & pathways | Testing: Terminations, testing & labeling',
    serve: 'Telecom contractors; Low-voltage installers; Systems integrators; IT infrastructure firms',
    deliverables: 'CSI Division 27 estimate; Drop count schedule; Material & labor summary',
    relatedServices: 'electrical-estimating; commercial-estimation',
    faqs: 'Q: Do you count data drops by location?\nA: Yes. Every drop is mapped and counted by room, outlet type and cabling grade.',
    status: 'Published',
  },
  {
    id: 'trd-interior-exterior-finishes',
    slug: 'interior-exterior-finishes',
    title: 'Interior & Exterior Finishes',
    parent: '—',
    tagline: 'Drywall, flooring, paint and finish scopes measured to the square foot.',
    h1: 'Interior & Exterior Finishes Estimating Services',
    metaTitle: 'Finishes Estimating Services | Drywall, Flooring & Paint',
    metaDescription: 'Interior and exterior finishes estimating — drywall, flooring, painting, ceilings and cladding measured room by room and priced to your market. 8–24 hour delivery.',
    intro: 'Finishes are where scope hides. A missed ceiling, an unpriced wall type or a wrong flooring waste factor can quietly erase the profit on a job. Modern Estimator delivers finishes estimating services that measure every wall, ceiling and floor by room, substrate and finish type.',
    scope: 'Walls & ceilings: Metal framing & drywall by type; Taping & finish levels; Acoustical & specialty ceilings | Floors: Tile, stone & grout; Carpet, LVT & sheet goods; Wood & laminate flooring | Paint: Interior paint by surface; Doors, frames & trim; Exterior siding & stucco',
    serve: 'Drywall & finish contractors; Flooring contractors; Painting contractors; General contractors',
    deliverables: 'CSI Division 09 estimate; Room-by-room finish schedule; Marked-up plans by finish',
    relatedServices: 'quantity-takeoff; residential-estimation; commercial-estimation',
    faqs: 'Q: Do you break finishes out by room?\nA: Yes. Every finishes estimate is organized by room and finish type.',
    status: 'Published',
  },
  {
    id: 'trd-drywall-takeoff-services',
    slug: 'drywall-takeoff-services',
    title: 'Drywall Takeoff Services',
    parent: 'Interior & Exterior Finishes',
    tagline: 'Board, framing, tape and finish quantified for every wall and ceiling.',
    h1: 'Drywall Takeoff & Estimating Services',
    metaTitle: 'Drywall Takeoff Services | Framing, Board & Compound',
    metaDescription: 'Drywall takeoff services for framing and drywall contractors — studs, track, gypsum board, compound and tape counted with waste factors.',
    intro: 'Our drywall takeoffs count every sheet, stud, track and pound of compound. We separate wall types, fire ratings and finish levels so pricing reflects the actual scope.',
    scope: 'Framing & board: Metal stud & track framing; Drywall sheets by type & rating | Finishing: Taping, mud & corner beads; Insulation & sound attenuation; Soffits & shaft walls',
    serve: 'Drywall contractors; Lath & plaster subs; General contractors',
    deliverables: 'CSI Division 09 drywall takeoff; Stud & board count sheet; Marked-up wall plans',
    relatedServices: 'interior-exterior-finishes; quantity-takeoff',
    faqs: 'Q: How do you handle fire-rated wall assemblies?\nA: We categorize each wall by UL assembly code, board layers and rating hour requirements.',
    status: 'Published',
  },
  {
    id: 'trd-flooring-estimating-services',
    slug: 'flooring-estimating-services',
    title: 'Flooring Estimating Services',
    parent: 'Interior & Exterior Finishes',
    tagline: 'Tile, carpet, LVT, hardwood and resilient flooring taken off by area and room.',
    h1: 'Flooring Takeoff & Estimating Services',
    metaTitle: 'Flooring Estimating Services | Tile, Carpet, LVT & Wood',
    metaDescription: 'Flooring takeoff and estimating services — tile, stone, carpet, LVT, hardwood and floor prep quantified room by room with waste factors.',
    intro: 'Detailed flooring estimates broken out by room, material type and substrate preparation. We apply realistic pattern and layout waste factors so you order accurately.',
    scope: 'Soft & resilient: Carpet & carpet tile; LVT, sheet vinyl & VCT | Tile & wood: Tile, stone & grout; Hardwood & engineered wood | Prep: Base, transition strips & floor prep',
    serve: 'Flooring contractors; Tile setters; Commercial interior specialists',
    deliverables: 'CSI Division 09 flooring takeoff; Room-by-room area schedule; Material order list with waste',
    relatedServices: 'interior-exterior-finishes; material-estimation',
    faqs: 'Q: Do you calculate waste factors for patterned tile?\nA: Yes. We apply material-specific waste factors (e.g. 10–15% for diagonal tile) transparently.',
    status: 'Published',
  },
  {
    id: 'trd-painting-estimating-services',
    slug: 'painting-estimating-services',
    title: 'Painting Estimating Services',
    parent: 'Interior & Exterior Finishes',
    tagline: 'Interior and exterior paint quantities, coats, surface prep and trim counted.',
    h1: 'Painting Estimating & Takeoff Services',
    metaTitle: 'Painting Estimating Services | Interior & Exterior Takeoffs',
    metaDescription: 'Painting takeoff services — wall area, ceiling area, doors, trim, primers, finish coats and prep labor estimated for commercial and residential painters.',
    intro: 'Complete paint takeoffs covering square footage, coat counts, surface preparation, primer and finish coats priced with local paint and labor rates.',
    scope: 'Interior: Interior walls & ceilings; Doors, frames & trim | Exterior: Exterior siding & masonry; Primers, sealers & coats | Prep: Surface prep, caulking & masking',
    serve: 'Painting contractors; Commercial painters; Fit-out contractors',
    deliverables: 'Painting estimate by surface type; Gallon count summary; Labor & equipment hours',
    relatedServices: 'interior-exterior-finishes; material-estimation',
    faqs: 'Q: How do you estimate trim and doors?\nA: Doors and frames are counted by unit; linear trim is measured by foot and converted to coat coverage.',
    status: 'Published',
  },
  {
    id: 'trd-masonry-estimating',
    slug: 'masonry-estimating',
    title: 'Masonry Estimating',
    parent: '—',
    tagline: 'Accurate CMU, brick, stone and mortar unit counts from wall types and elevations.',
    h1: 'Masonry Estimating Services',
    metaTitle: 'Masonry Estimating Services | CMU, Brick & Stone Takeoffs',
    metaDescription: 'Masonry estimating and takeoff services for CMU, brick, stone veneer, mortar, grout and reinforcing — unit counts from elevations priced in 8–24 hours.',
    intro: 'Masonry bids live or die on unit counts. Modern Estimator provides masonry estimating services that count every block, brick and stone from elevations and wall types.',
    scope: 'Units: CMU by size & wall type; Brick & modular units; Stone veneer | Reinforcing: Grout & reinforced cells; Vertical & horizontal rebar | Accessories: Mortar, ties, flashing & weeps',
    serve: 'Masonry contractors; Block & brick masons; General contractors',
    deliverables: 'CSI Division 04 workbook; Unit count by wall & elevation; Rebar & grout summary',
    relatedServices: 'quantity-takeoff; material-estimation; commercial-estimation',
    faqs: 'Q: Do you calculate grout fill volume?\nA: Yes. We calculate cubic yards of grout based on cell size and lift height.',
    status: 'Published',
  },
  {
    id: 'trd-mep-estimating',
    slug: 'mep-estimating',
    title: 'MEP Estimating',
    parent: '—',
    tagline: 'Coordinated Mechanical, Electrical and Plumbing packages from trade specialists.',
    h1: 'MEP Estimating Services',
    metaTitle: 'MEP Estimating Services | Mechanical, Electrical & Plumbing',
    metaDescription: 'Coordinated MEP estimating services from trade-specialist estimators — HVAC, plumbing, piping and electrical quantified in one bid-ready package.',
    intro: 'MEP is the most detail-heavy part of any estimate and the most common place for scope gaps between trades. We deliver coordinated mechanical, electrical and plumbing takeoffs.',
    scope: 'HVAC: Ductwork, equipment & controls | Plumbing: Fixtures, piping & drains | Electrical: Distribution, lighting & devices',
    serve: 'MEP contractors; General contractors; Construction managers',
    deliverables: 'Unified MEP Excel workbook; Trade-by-trade cost summary; Marked-up MEP drawings',
    relatedServices: 'quantity-takeoff; commercial-estimation; bid-preparation',
    faqs: 'Q: Can I get just one MEP trade estimated?\nA: Yes. We offer standalone mechanical, electrical and plumbing takeoffs.',
    status: 'Published',
  },
  {
    id: 'trd-mechanical-estimating',
    slug: 'mechanical-estimating',
    title: 'Mechanical Estimating',
    parent: 'MEP Estimating',
    tagline: 'HVAC equipment, ductwork, piping and controls quantified and priced.',
    h1: 'Mechanical & HVAC Systems Estimating',
    metaTitle: 'Mechanical Estimating Services | HVAC Equipment & Ductwork',
    metaDescription: 'Mechanical estimating services for HVAC contractors — chillers, RTUs, ductwork, hydronic piping, dampers and controls priced to your market.',
    intro: 'HVAC equipment, ductwork weight by gauge, fittings and temperature control systems priced to your regional material and labor rates.',
    scope: 'Equipment: Air handling units, RTUs & chillers | Ductwork: Ductwork & fittings by gauge | Piping: Hydronic piping & pumps',
    serve: 'Mechanical contractors; HVAC installers; Sheet metal shops',
    deliverables: 'CSI Division 23 mechanical estimate; Duct weight & equipment schedule; Labor summary',
    relatedServices: 'mep-estimating; duct-takeoff-services',
    faqs: 'Q: How do you measure sheet metal ductwork?\nA: By surface area and gauge, applying pound conversion factors per SMACNA standards.',
    status: 'Published',
  },
  {
    id: 'trd-hvac-estimating',
    slug: 'hvac-estimating',
    title: 'HVAC Estimating',
    parent: 'MEP Estimating',
    tagline: 'Ductwork tonnage, equipment, grilles and controls measured from mechanical plans.',
    h1: 'HVAC Estimating Services',
    metaTitle: 'HVAC Estimating Services | Ductwork & Equipment Takeoffs',
    metaDescription: 'HVAC takeoff and estimating services — duct weight, fitting counts, RTUs, split systems, diffusers and insulation measured from mechanical drawings.',
    intro: 'Complete HVAC takeoffs covering air distribution, sheet metal poundage, equipment and insulation.',
    scope: 'Ductwork: Supply, return & exhaust ductwork | Fittings: Sheet metal fittings & transitions | Air devices: Diffusers, registers & grilles',
    serve: 'HVAC contractors; Mechanical subs; Air balance specialists',
    deliverables: 'HVAC takeoff & cost estimate; Sheet metal poundage list; Equipment schedule',
    relatedServices: 'mep-estimating; mechanical-estimating',
    faqs: 'Q: Do you include air balance and commissioning?\nA: Yes, itemized under project closeout allowances.',
    status: 'Published',
  },
  {
    id: 'trd-duct-takeoff-services',
    slug: 'duct-takeoff-services',
    title: 'Duct Takeoff Services',
    parent: 'MEP Estimating',
    tagline: 'Sheet metal ductwork pounds, square footage and fittings counted by gauge.',
    h1: 'Sheet Metal Duct Takeoff Services',
    metaTitle: 'Duct Takeoff Services | Sheet Metal Weight & Fitting Counts',
    metaDescription: 'Sheet metal duct takeoff services — rectangular, round and spiral duct weight by gauge, fittings, dampers and lining calculated in 8–24 hours.',
    intro: 'Sheet metal ductwork taken off by gauge, pressure class and dimension with exact fitting counts.',
    scope: 'Duct types: Rectangular, round & spiral ductwork | Fittings: Elbows, tees, reducers & transitions | Accessories: Dampers, vanes, flex duct & hangers',
    serve: 'Sheet metal fabricators; Duct installers; HVAC contractors',
    deliverables: 'Detailed duct takeoff spreadsheet; Weight break by gauge & size; Fitting summary sheet',
    relatedServices: 'hvac-estimating; mechanical-estimating',
    faqs: 'Q: What duct pressure classes do you support?\nA: Low, medium and high pressure SMACNA classes.',
    status: 'Published',
  },
  {
    id: 'trd-plumbing-estimating',
    slug: 'plumbing-estimating',
    title: 'Plumbing Estimating',
    parent: 'MEP Estimating',
    tagline: 'Water, waste, vent, gas lines and fixture counts from plumbing riser diagrams.',
    h1: 'Plumbing Estimating & Takeoff Services',
    metaTitle: 'Plumbing Estimating Services | Piping, Fixtures & Risers',
    metaDescription: 'Plumbing estimating services — water supply, sanitary waste, vent lines, gas piping, fixtures and water heaters estimated from plans and riser diagrams.',
    intro: 'Plumbing takeoffs covering domestic water, waste, vent, gas, fixtures and equipment from plans and riser diagrams.',
    scope: 'Piping: Domestic cold & hot water piping; Sanitary waste & vent piping | Fixtures: Plumbing fixtures & trim | Gas & equipment: Natural gas piping; Water heaters & pumps',
    serve: 'Plumbing contractors; Piping subs; Commercial mechanical firms',
    deliverables: 'CSI Division 22 plumbing estimate; Fixture & pipe takeoff schedule; Material & labor summary',
    relatedServices: 'mep-estimating; piping-estimating',
    faqs: 'Q: Do you count pipe fittings?\nA: Yes. Elbows, tees, cleanouts and valves are itemized by pipe diameter.',
    status: 'Published',
  },
  {
    id: 'trd-piping-estimating',
    slug: 'piping-estimating',
    title: 'Piping Estimating',
    parent: 'MEP Estimating',
    tagline: 'Process, hydronic and utility piping taken off by size, schedule and material.',
    h1: 'Industrial & Process Piping Estimating',
    metaTitle: 'Piping Estimating Services | Process & Hydronic Piping',
    metaDescription: 'Piping takeoff services — copper, carbon steel, stainless steel and PVC piping runs, valves, strainers, hangers and weld counts priced to your market.',
    intro: 'Process, hydronic and industrial piping runs measured with valve schedules, fittings and weld counts.',
    scope: 'Piping runs: Hydronic heating & chilled water piping; Compressed air & fuel piping | Specialties: Valves, strainers & hangers | Labor: Welding & joint counts',
    serve: 'Piping contractors; Process piping firms; Industrial mechanical subs',
    deliverables: 'Piping takeoff & pricing workbook; Valve & fitting schedule; Weld count & labor units',
    relatedServices: 'plumbing-estimating; mechanical-estimating',
    faqs: 'Q: Do you calculate weld inch units?\nA: Yes. Weld inch quantities are calculated by pipe diameter and wall schedule.',
    status: 'Published',
  },
  {
    id: 'trd-gutter-estimating',
    slug: 'gutter-estimating',
    title: 'Gutter Estimating Services',
    parent: 'MEP Estimating',
    tagline: 'Commercial and residential gutter, downspout and drainage takeoffs.',
    h1: 'Gutter & Roof Drainage Estimating',
    metaTitle: 'Gutter Estimating Services | Downspouts & Scuppers',
    metaDescription: 'Gutter takeoff services — seamless gutters, downspouts, conductor heads, scuppers and accessories quantified for commercial and residential contractors.',
    intro: 'Linear footage, downspouts, conductor heads and custom flashing for roof drainage systems.',
    scope: 'Gutters: Commercial & residential gutters | Drainage: Downspouts & conductor heads; Scuppers & overflow drains | Hardware: Hangers, elbows & splash blocks',
    serve: 'Gutter installers; Sheet metal contractors; Roofing subs',
    deliverables: 'Gutter takeoff & quote summary; Linear footage & fitting count; Material order sheet',
    relatedServices: 'roofing-estimating; thermal-moisture-protection-estimating',
    faqs: 'Q: Do you price custom copper or aluminum gutters?\nA: Yes, we adjust for material gauge and metal type.',
    status: 'Published',
  },
  {
    id: 'trd-metals-estimating',
    slug: 'metals-estimating',
    title: 'Metals Estimating Services',
    parent: '—',
    tagline: 'Structural steel, rebar, metal deck, stairs, railings and miscellaneous metals.',
    h1: 'Metals Estimating Services',
    metaTitle: 'Metals Estimating Services | Steel, Rebar & Misc. Metals',
    metaDescription: 'Metals estimating and takeoff services — structural steel tonnage, rebar, metal deck, stairs, railings and miscellaneous metals priced for fabrication and erection.',
    intro: 'Steel is priced by the pound, so every missed member matters. Modern Estimator provides metals estimating services that take off structural steel, reinforcing, metal deck and misc metals.',
    scope: 'Structural: Structural steel beams, columns & trusses | Deck & rebar: Metal deck & shear studs; Rebar by size & weight | Misc metals: Miscellaneous metals, stairs & railings',
    serve: 'Steel fabricators; Steel erectors; Rebar placers; General contractors',
    deliverables: 'CSI Division 05 metals estimate; Steel tonnage & rebar weight summary; Misc metals schedule',
    relatedServices: 'quantity-takeoff; commercial-estimation; material-estimation',
    faqs: 'Q: Do you estimate connection steel?\nA: Yes. Shear plates, clip angles and gussets are calculated as a percentage or detailed count.',
    status: 'Published',
  },
  {
    id: 'trd-rebar-estimating',
    slug: 'rebar-estimating',
    title: 'Rebar Estimating Services',
    parent: 'Metals Estimating Services',
    tagline: 'Reinforcing steel tonnage, bar lists, stirrups and mesh taken off per element.',
    h1: 'Rebar Takeoff & Bending List Estimating',
    metaTitle: 'Rebar Estimating Services | Bar Lists & Tonnage Takeoffs',
    metaDescription: 'Rebar takeoff services for placers and fabricators — bar sizes #3 to #18, grades, stirrups, ties, mesh and weight calculated by structural element.',
    intro: 'Bar-by-bar rebar scheduling with tonnage by size, grade and structural element.',
    scope: 'Bar sizes: Deformed bar by size (#3 to #18); Rebar grade (Grade 60, epoxy) | Mesh & ties: Welded wire reinforcement; Stirrups, ties & dowels | Waste: Lap lengths & waste factors',
    serve: 'Rebar placers; Steel fabricators; Concrete contractors',
    deliverables: 'Rebar takeoff & bending list; Weight summary by bar size; Placement & accessory list',
    relatedServices: 'concrete-estimating; metals-estimating',
    faqs: 'Q: Do you include lap splices per ACI standards?\nA: Yes. Tension and compression lap lengths are applied according to the structural notes.',
    status: 'Published',
  },
  {
    id: 'trd-structural-steel-estimating-services',
    slug: 'structural-steel-estimating-services',
    title: 'Structural Steel Estimating Services',
    parent: 'Metals Estimating Services',
    tagline: 'Fabrication and erection steel tonnage, connection plates and joist takeoffs.',
    h1: 'Structural Steel Takeoff & Erection Estimating',
    metaTitle: 'Structural Steel Estimating | Beams, Columns & Joists',
    metaDescription: 'Structural steel estimating services — W-shapes, HSS columns, steel joists, deck and connection steel priced for fabrication and field erection.',
    intro: 'Structural member weights, connection plates, joists and erection labor for steel fabricators and erectors.',
    scope: 'Members: W-shapes, channels, angles & HSS | Joists & deck: Steel joists & joist girders; Metal roof & floor deck | Labor: Shop primer & erection labor',
    serve: 'Structural steel fabricators; Steel erectors; General contractors',
    deliverables: 'Structural steel bid package; Tonnage takeoff by member type; Fabrication & erection estimate',
    relatedServices: 'metals-estimating; commercial-estimation',
    faqs: 'Q: Do you calculate crane and rigging hours for erection?\nA: Yes. Erection labor includes crane day rates and crew hours.',
    status: 'Published',
  },
  {
    id: 'trd-openings-estimating',
    slug: 'openings-estimating',
    title: 'Openings Estimating Services',
    parent: '—',
    tagline: 'Doors, frames, hardware sets, windows, storefront and curtain wall counted.',
    h1: 'Openings Estimating Services',
    metaTitle: 'Openings Estimating Services | Doors, Windows & Glazing',
    metaDescription: 'Openings estimating services — doors, frames, hardware sets, windows, storefront and curtain wall counted from schedules and priced in 8–24 hours.',
    intro: 'Openings are a schedule-driven scope where one missed hardware set or mis-sized frame causes real problems. Modern Estimator provides openings estimating services that count every door and window.',
    scope: 'Doors & frames: Hollow metal & wood doors; Steel & aluminum frames | Hardware: Hardware sets by schedule | Glazing: Windows, storefront & curtain wall',
    serve: 'Door & hardware distributors; Glazing contractors; Storefront installers',
    deliverables: 'CSI Division 08 openings estimate; Door & hardware schedule matrix; Glazing breakdown',
    relatedServices: 'quantity-takeoff; commercial-estimation; bid-preparation',
    faqs: 'Q: How do you verify hardware schedules?\nA: We cross-reference architectural door schedules against hardware specifications line by line.',
    status: 'Published',
  },
  {
    id: 'trd-thermal-moisture-protection-estimating',
    slug: 'thermal-moisture-protection-estimating',
    title: 'Thermal & Moisture Protection Estimating',
    parent: '—',
    tagline: 'Division 07 estimating — roofing, insulation, waterproofing, air barriers and sealants.',
    h1: 'Thermal & Moisture Protection Estimating Services',
    metaTitle: 'Thermal & Moisture Protection Estimating | Division 07',
    metaDescription: 'Division 07 estimating services — roofing, insulation, waterproofing, air barriers, sealants and fireproofing measured from details and priced to your market.',
    intro: 'Division 07 protects the entire building, and it is one of the easiest divisions to under-scope. We provide thermal and moisture protection estimating services.',
    scope: 'Roofing: Commercial & residential roofing | Insulation: Rigid & batt insulation | Barriers: Below-grade waterproofing; Air & vapor barriers; Joint sealants',
    serve: 'Roofing contractors; Waterproofing subs; Insulation installers',
    deliverables: 'CSI Division 07 estimate; Square footage schedule by roof & wall area; Flashing breakdown',
    relatedServices: 'quantity-takeoff; material-estimation; commercial-estimation',
    faqs: 'Q: Do you take off membrane flashings at parapets?\nA: Yes. Parapets, curbs and penetration flashings are measured in linear feet.',
    status: 'Published',
  },
  {
    id: 'trd-insulation-estimating-services',
    slug: 'insulation-estimating-services',
    title: 'Insulation Estimating Services',
    parent: 'Thermal & Moisture Protection Estimating',
    tagline: 'Batt, blown-in, spray foam and rigid board insulation measured by area and R-value.',
    h1: 'Building Insulation Takeoff & Estimating',
    metaTitle: 'Insulation Estimating Services | Spray Foam, Batt & Board',
    metaDescription: 'Insulation takeoff services — fiberglass batts, spray foam (SPF), rigid polyiso and pipe insulation measured by square footage and R-value.',
    intro: 'Thermal and acoustical insulation takeoffs categorized by R-value, material type and location.',
    scope: 'Thermal: Fiberglass batt & mineral wool; Spray polyurethane foam (SPF) | Rigid & pipe: Rigid board (XPS/Polyiso); Pipe & duct thermal insulation | Acoustic: Sound attenuation batts',
    serve: 'Insulation contractors; Spray foam installers; Drywall & framing subs',
    deliverables: 'Insulation takeoff spreadsheet; Square footage by R-value; Material order & labor estimate',
    relatedServices: 'thermal-moisture-protection-estimating; drywall-takeoff-services',
    faqs: 'Q: How do you handle board feet for spray foam?\nA: Board feet are calculated based on target thickness (e.g. 2" closed cell = 2 board feet/sq ft).',
    status: 'Published',
  },
  {
    id: 'trd-roofing-estimating',
    slug: 'roofing-estimating',
    title: 'Roofing Estimating Services',
    parent: 'Thermal & Moisture Protection Estimating',
    tagline: 'Single-ply, metal, shingle and built-up roofing estimates with flashings.',
    h1: 'Commercial & Residential Roofing Estimating',
    metaTitle: 'Roofing Estimating Services | TPO, EPDM, Metal & Shingles',
    metaDescription: 'Roofing takeoff services — TPO, EPDM, standing seam metal, asphalt shingles, roof insulation board and flashing accessories measured from drawings.',
    intro: 'Commercial and residential roof square counts, pitch adjustments, membrane, insulation and edge metal accessories.',
    scope: 'Membranes: TPO, EPDM & PVC single-ply membranes; Asphalt shingles & tile | Metal: Standing seam metal roofing | Insulation: Roof insulation & cover board',
    serve: 'Commercial roofing contractors; Residential roofers; Sheet metal installers',
    deliverables: 'Roofing estimate workbook; Square count & pitch calculation; Accessory list',
    relatedServices: 'thermal-moisture-protection-estimating; gutter-estimating',
    faqs: 'Q: Do you account for roof pitch slope factors?\nA: Yes. Pitch multipliers are applied to flat plan area measurements.',
    status: 'Published',
  },
  {
    id: 'trd-fireproofing-estimating-services',
    slug: 'fireproofing-estimating-services',
    title: 'Fireproofing Estimating Services',
    parent: 'Thermal & Moisture Protection Estimating',
    tagline: 'Intumescent paint and sprayed fire-resistive materials (SFRM) measured by beam.',
    h1: 'Fireproofing & Intumescent Coating Estimating',
    metaTitle: 'Fireproofing Estimating Services | SFRM & Intumescent Paint',
    metaDescription: 'Fireproofing takeoff services — cementitious SFRM and intumescent paint coverage calculated from structural steel member sizes and hourly ratings.',
    intro: 'Sprayed fire-resistive material and intumescent coating coverage calculated from structural steel member sizes.',
    scope: 'Materials: Cementitious & fibrous SFRM; Intumescent fire-resistive coatings | Ratings: Hourly rating matching (1-hr, 2-hr, 3-hr) | Factors: Over-spray & thickness factors',
    serve: 'Fireproofing contractors; Specialty coating subs; Steel erectors',
    deliverables: 'Fireproofing takeoff sheet; Board foot / square foot summary; Material thickness & labor cost',
    relatedServices: 'thermal-moisture-protection-estimating; structural-steel-estimating-services',
    faqs: 'Q: How do you calculate W/D ratios for intumescent paint?\nA: We compute member W/D ratios from steel tables to determine required DFT thickness.',
    status: 'Published',
  },
  {
    id: 'trd-sitework-estimating',
    slug: 'sitework-estimating',
    title: 'Sitework Estimating Services',
    parent: '—',
    tagline: 'Demolition, cut/fill earthwork, site utilities, paving, curbs and site improvements.',
    h1: 'Sitework Estimating Services',
    metaTitle: 'Sitework Estimating Services | Earthwork, Utilities & Paving',
    metaDescription: 'Sitework estimating services — demolition, cut/fill earthwork, site utilities, paving, curbs and site improvements quantified from civil drawings. 8–24 hour turnaround.',
    intro: 'Sitework carries the biggest unknowns on a project, so accurate quantities matter more here than anywhere else. Modern Estimator provides sitework estimating services directly from civil drawings.',
    scope: 'Earthwork: Site clearing & earthwork cut/fill | Utilities: Storm & sanitary sewer utilities; Water mains & service lines | Paving: Asphalt paving, concrete curbs & sidewalks',
    serve: 'Sitework contractors; Earthwork subs; Utility contractors; Paving firms',
    deliverables: 'CSI Division 31-33 sitework estimate; Cut/fill volume summary; Utility pipe schedule',
    relatedServices: 'quantity-takeoff; commercial-estimation; material-estimation',
    faqs: 'Q: How do you calculate cut and fill earthwork?\nA: We digitize grading contours to calculate net cut/fill volumes in cubic yards.',
    status: 'Published',
  },
  {
    id: 'trd-landscaping-estimating-services',
    slug: 'landscaping-estimating-services',
    title: 'Landscaping Estimating Services',
    parent: 'Sitework Estimating Services',
    tagline: 'Hardscape, plantings, irrigation and sod measured from landscape plans.',
    h1: 'Landscape & Hardscape Takeoff Estimating',
    metaTitle: 'Landscaping Estimating Services | Plants, Sod & Irrigation',
    metaDescription: 'Landscaping takeoff services — plant counts, sod square footage, irrigation piping & heads, topsoil volumes and paver hardscaping quantified.',
    intro: 'Plant counts, turf area, topsoil volumes, irrigation heads and paver hardscaping quantified from landscape plans.',
    scope: 'Plantings: Trees, shrubs & groundcover counts; Sod, hydroseed & topsoil depth | Irrigation: Irrigation piping, valves & heads | Hardscape: Pavers, retaining walls & edging',
    serve: 'Landscape contractors; Hardscape installers; Irrigation specialists',
    deliverables: 'Landscaping takeoff & cost sheet; Plant count schedule; Material volume breakdown',
    relatedServices: 'sitework-estimating; material-estimation',
    faqs: 'Q: Do you count plant container sizes?\nA: Yes, plants are categorized by 1-gal, 5-gal, 15-gal or box tree size.',
    status: 'Published',
  },
  {
    id: 'trd-lumber-takeoff',
    slug: 'lumber-takeoff',
    title: 'Lumber Takeoff Services',
    parent: '—',
    tagline: 'Lumber takeoff services for framers and builders — studs, joists, rafters and sheathing.',
    h1: 'Lumber Takeoff Services',
    metaTitle: 'Lumber Takeoff Services | Framing Material Lists in 8–24 Hrs',
    metaDescription: 'Lumber takeoff services for framers and builders — studs, plates, headers, joists, rafters, sheathing and engineered lumber counted stick by stick. 8–24 hours.',
    intro: 'A lumber list that is off by a few percent means either a short crew or a pile of waste on site. Modern Estimator provides lumber takeoff services that count every stud, plate, header, joist and sheet.',
    scope: 'Walls: Wall studs, plates & headers | Floors & roofs: Floor joists, I-joists & trusses; Roof rafters, hips & valleys | Sheathing: OSB & plywood sheathing; Engineered lumber (LVL, PSL)',
    serve: 'Framing contractors; Home builders; Lumber yards; Component manufacturers',
    deliverables: 'Stick-by-stick lumber list; Cut list & length optimization; Sheathing sheet count & waste',
    relatedServices: 'material-estimation; residential-estimation; quantity-takeoff',
    faqs: 'Q: Are lumber lengths optimized for ordering?\nA: Yes. Board lengths (10\', 12\', 16\', 20\') are optimized to minimize jobsite scrap.',
    status: 'Published',
  },
  {
    id: 'trd-wood-plastic-composites-estimating',
    slug: 'wood-plastic-composites-estimating',
    title: 'Wood & Plastic Composites Estimating',
    parent: 'Lumber Takeoff Services',
    tagline: 'Rough carpentry, composite decking, architectural woodwork and plastic fabrications.',
    h1: 'Rough Carpentry & Composite Decking Estimating',
    metaTitle: 'Wood & Plastic Composites Estimating | Decking & Carpentry',
    metaDescription: 'Division 06 estimating services — rough carpentry, blocking, composite decking systems, PVC trim and plastic fabrications.',
    intro: 'Rough carpentry, exterior PVC trim, composite decking systems and structural plastic fabrications.',
    scope: 'Carpentry: Rough carpentry & blocking; Composite decking & railing systems | Trim: PVC exterior trim & fascia; Plastic fabrications & wall paneling',
    serve: 'Deck builders; Carpentry contractors; Exterior trim installers',
    deliverables: 'CSI Division 06 estimate; Decking & framing takeoff sheet; Material list with fasteners',
    relatedServices: 'lumber-takeoff; residential-estimation',
    faqs: 'Q: Do you count hidden deck fasteners and clips?\nA: Yes, hidden clip counts are calculated based on joist spacing and deck square footage.',
    status: 'Published',
  },
  {
    id: 'trd-millwork-estimating',
    slug: 'millwork-estimating',
    title: 'Millwork Estimating Services',
    parent: 'Lumber Takeoff Services',
    tagline: 'Custom casework, cabinets, trim, moulding and architectural wood paneling.',
    h1: 'Millwork & Architectural Casework Estimating',
    metaTitle: 'Millwork Estimating Services | Casework, Cabinets & Trim',
    metaDescription: 'Millwork takeoff services — commercial casework, cabinets, solid surface countertops, running trim, moulding and architectural wood paneling estimated in 8–24 hours.',
    intro: 'Custom architectural millwork, commercial casework, countertops, running trim and decorative wall paneling.',
    scope: 'Casework: Commercial casework & cabinets; Plastic laminate & solid surface tops | Trim: Standing & running trim/moulding; Architectural wall paneling',
    serve: 'Millwork fabricators; Casework installers; Commercial interior subs',
    deliverables: 'Millwork & casework estimate; Linear & square foot itemization; Hardware breakdown',
    relatedServices: 'lumber-takeoff; commercial-estimation',
    faqs: 'Q: How do you price custom reception desks or feature walls?\nA: Custom items are broken down into material substrate, laminate/veneer, hardware and shop assembly hours.',
    status: 'Published',
  },
];

export async function GET() {
  try {
    const tradesRef = collection(db, 'trades');
    const snapshot = await getDocs(tradesRef);

    let trades = snapshot.docs.map((d) => ({
      ...d.data(),
      id: d.id,
    }));

    // If database trades collection is empty, auto-seed with all 29 trade pages!
    if (trades.length === 0) {
      console.log('Seeding initial 29 trade estimating pages into Firestore DB...');
      for (const trd of ALL_TRADES) {
        await setDoc(doc(db, 'trades', trd.id), trd);
      }
      trades = ALL_TRADES;
    }

    return NextResponse.json({ trades });
  } catch (error) {
    console.error('Error fetching trades:', error);
    return NextResponse.json({ error: 'Failed to fetch trades', details: error.message }, { status: 500 });
  }
}

export async function POST(request) {
  try {
    const body = await request.json();
    const {
      title, slug, parent, tagline, h1, metaTitle, metaDescription,
      intro, scope, serve, deliverables, relatedServices, faqs, status
    } = body;

    if (!title || !title.trim()) {
      return NextResponse.json({ error: 'Trade title is required' }, { status: 400 });
    }

    const cleanSlug = (slug || title).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const tradeId = `trd-${cleanSlug || Date.now().toString(36)}`;

    const newTrade = {
      id: tradeId,
      slug: cleanSlug,
      title: title.trim(),
      parent: parent ? parent.trim() : '—',
      tagline: tagline ? tagline.trim() : '',
      h1: h1 ? h1.trim() : `${title.trim()} Services`,
      metaTitle: metaTitle ? metaTitle.trim() : `${title.trim()} | Modern Estimator`,
      metaDescription: metaDescription ? metaDescription.trim() : (tagline ? tagline.trim() : ''),
      intro: intro ? intro.trim() : '',
      scope: scope ? scope.trim() : '',
      serve: serve ? serve.trim() : '',
      deliverables: deliverables ? deliverables.trim() : '',
      relatedServices: relatedServices ? relatedServices.trim() : '',
      faqs: faqs ? faqs.trim() : '',
      status: status || 'Published',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await setDoc(doc(db, 'trades', tradeId), newTrade);

    return NextResponse.json({ success: true, trade: newTrade });
  } catch (error) {
    console.error('Error creating trade:', error);
    return NextResponse.json({ error: 'Failed to create trade', details: error.message }, { status: 500 });
  }
}
